name: Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-darwin:
    strategy:
      matrix:
        os: [ macos-12 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nix
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: ttak0422-vim-plugins-overlay
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Push inputs
        run: |
          nix flake archive --json \
          | jq -r '.path,(.inputs|to_entries[].value.path)' \
          | cachix push ttak0422-vim-plugins-overlay
      
      - name: Check flake
        run: |
          nix flake check --commit-lock-file
          git push

      - name: Build
        run: nix flake show --json | jq '.packages."x86_64-linux"|keys[]'| xargs -I {} nix build .#{}
