name: Cache
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-darwin:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Filter
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            flake:
              - 'flake.nix'

      - name: Setup Nix
        if: steps.changes.outputs.flake == 'true'
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cachix
        if: steps.changes.outputs.flake == 'true'
        uses: cachix/cachix-action@v11
        with:
          name: ttak0422-vim-plugins-overlay
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Check flake
        if: steps.changes.outputs.flake == 'true'
        run: |
          nix flake check
