name: Update
on:
  schedule:
    - cron: "0 0 * * *" # UTC
  workflow_dispatch:
jobs:
  update-flake:
    strategy:
      matrix:
        os: [ ubuntu-latest macos-12 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: ttak0422-vim-plugins-overlay
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Update flake
        uses: DeterminateSystems/update-flake-lock@v3

      - name: Merge PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge ${{ steps.cpr.outputs.pull-request-url }} --merge
