name: Update
on:
  schedule:
    - cron: "0 0 * * *" # UTC
  workflow_dispatch:
jobs:
  update-flake:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Generate github token
        id: generate_token
        uses: actions/github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: ttak0422-vim-plugins-overlay
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: DeterminateSystems/update-flake-lock@v21
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - name: Setup merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --auto --delete-branch --squash "update_flake_lock_action"
