name: Update
on:
  schedule:
    - cron: "0 0 * * *" # UTC
  workflow_dispatch:
jobs:
  update-flake:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nix
        uses: cachix/install-nix-action@v22

      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: ttak0422-vim-plugins-overlay
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Update flake
        uses: DeterminateSystems/update-flake-lock@v19
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --auto --delete-branch --squash "update_flake_lock_action"
